name: Deploy
on: [workflow_dispatch]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        #password: ${{ secrets.SSH_PASSWORD }}
        key: ${{ secrets.KEY }}
  
        port: 22
        script: cd /home/www/testcd && git pull